### ISSUE TITLE
Escape breaks fullscreen view

### ISSUE THREAD

**Issue by fmaul** [BenjaminBrandmeier/ng2imggallery#1]
Great work Benjamin ;-) .. I found an issue though:

1. Click to open an image and view the image
2. Press Escape to close the image view
3. Try to click on another image

No other image opens by clicking anymore.

Tested on Chrome 53.0.2767.4 dev-m (64-bit)

**Comment by BenjaminBrandmeier** [comment]
Thanks Florian. Took me some time to continue the work on this project .. :)

I fixed this issue in current master.
